# Element-wise operations

In [1]:
import numpy as np

In [3]:
x = np.random.randint(30,size=(2,4))
x

array([[15, 16, 28, 13],
       [11, 23, 27,  3]])

In [4]:
y = np.random.randint(30,size=(2,4))
y

array([[17,  7, 11, 29],
       [20, 22, 25, 15]])

In [5]:
x+y

array([[32, 23, 39, 42],
       [31, 45, 52, 18]])

In [7]:
x = np.random.randint(5,size=(2,4))
x

array([[3, 1, 0, 1],
       [4, 2, 1, 2]])

In [8]:
y = np.random.randint(5,size=(2,4))
y

array([[0, 2, 4, 2],
       [4, 0, 1, 0]])

In [9]:
x*y

array([[ 0,  2,  0,  2],
       [16,  0,  1,  0]])

# Broadcasting

In [10]:
x = np.random.random((4,5))*10
x

array([[3.35600494, 2.35151261, 6.61965025, 8.9917111 , 2.14241962],
       [8.9948319 , 7.46788472, 8.16415847, 9.17720229, 3.03064237],
       [6.0949322 , 9.88014417, 3.43248085, 4.35421604, 9.50239629],
       [4.78444967, 0.01342417, 7.13737266, 7.7284056 , 5.24221046]])

In [13]:
y = np.random.random(5)*10
y

array([4.75840228, 2.24450073, 2.66918336, 2.49770748, 2.47533535])

In [14]:
y.shape

(5,)

In [15]:
z = np.maximum(x,y) # 对y进行广播，逐元素对比获取较大者
z

array([[4.75840228, 2.35151261, 6.61965025, 8.9917111 , 2.47533535],
       [8.9948319 , 7.46788472, 8.16415847, 9.17720229, 3.03064237],
       [6.0949322 , 9.88014417, 3.43248085, 4.35421604, 9.50239629],
       [4.78444967, 2.24450073, 7.13737266, 7.7284056 , 5.24221046]])

# Tensor dot

## Vector dot

In [16]:
x = np.random.randint(5,size=(3,))
x

array([4, 4, 1])

In [17]:
y = np.random.randint(5,size=(3,))
y

array([1, 4, 4])

In [18]:
x.dot(y)

24

# Matrix_vector dot

In [19]:
x = np.random.randint(5,size=(2,3))
x

array([[2, 2, 4],
       [0, 3, 0]])

In [26]:
y = np.random.randint(5,size=(3,))
y

array([4, 0, 1])

In [23]:
z = x.dot(y) # x的每一行与y求内积，相加。
z

array([8, 0])

In [25]:
z.ndim

1

In [27]:
# Matrix dot

In [31]:
x = np.random.randint(5,size=(2,3))
x

array([[3, 1, 4],
       [4, 1, 3]])

In [32]:
y = np.random.random((3,2))
y

array([[0.90452726, 0.65751644],
       [0.3185642 , 0.14925527],
       [0.67001564, 0.86345097]])

In [33]:
z = np.dot(x,y) # 正常的矩阵相乘
z

array([[5.71220853, 5.57560845],
       [5.94672016, 5.36967392]])

# Tensor reshaping

关于高维转置的事
+ 如(2,30,20)经过转置后的维度变成怎样了？实际上是倒转过来了，变为了(20,30,2)
+ 那么对于4维的，是不是也一样呢？如(2,30,40,50)-->(50,40,30,2)

### 对于高维转置中数值是如何转换的，若忘记了，可听老师课程。
https://www.bilibili.com/video/av85562236?p=9


In [36]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [37]:
train_images.shape

(60000, 28, 28)

In [38]:
train_images = train_images.reshape(60000,28*28)

In [39]:
train_images.shape

(60000, 784)

In [42]:
x = np.zeros((3,4))
print(x.shape)
print(x.T.shape) # print(np.transpose(x))

(3, 4)
(4, 3)


In [44]:
# 3维转置
x = np.zeros((3,4,5))
print(x.shape)
print(np.transpose(x).shape)

(3, 4, 5)
(5, 4, 3)


In [43]:
# 4维转置
x = np.zeros((3,4,7,10))
print(x.shape)
print(x.T.shape)

(3, 4, 7, 10)
(10, 7, 4, 3)


# 实例

In [2]:
y = np.arange(24).reshape(2,3,4)
print(y.shape)
print(y)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [46]:
z = np.transpose(y)
print(z.shape)# 但具体z的数字变成这样了？

(4, 3, 2)


In [47]:
# another example
# 经过0,2,1转换后的的维度为(2,4,3)
z = np.transpose(y,(0,2,1))# 指定交换轴
print(z.shape)
z

(2, 4, 3)


array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])